plugins {
    id 'com.android.application'
}

android {
    namespace 'fr.techplanner.app'
    compileSdk 36

    defaultConfig {
        applicationId 'fr.techplanner.app'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
            resValue 'string', 'app_name', 'TechPlanner Test'
        }
        release {
            minifyEnabled false
            resValue 'string', 'app_name', 'TechPlanner'
        }
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.7.3'
}
